### ISSUE TITLE
Seems like fuck alias isn't configured!

### ISSUE THREAD

**Issue by aloner-pro** [nvbn/thefuck#1127]
#Seems like fuck alias isn't configured!
system - Windows 10
followed installation process but can't understand what this means.
![Annotation 2020-08-14 165738](https://user-images.githubusercontent.com/69566363/90244979-6bc3d400-de4f-11ea-9753-8288e17c355c.png)

**Comment by divykj** [comment]
As far as I know, you'll have to use **powershell**.
Follow this to configure it in powershell: [Powershell Alias](https://github.com/nvbn/thefuck/wiki/Shell-aliases#powershell)

**Comment by JacksonBurns** [comment]
Also see this repository for running in powershell: [Powershell Fuck (PoShFuck)](https://github.com/mattparkes/PoShFuck)

**Comment by ramykl** [comment]
> Also see this repository for running in powershell: [Powershell Fuck (PoShFuck)](https://github.com/mattparkes/PoShFuck)

This repository seems broken and not maintained. The example doesn't work and just keeps returning the broken command rather than the "fixed" one. 

Would be nice to have some more instructions for getting this working on windows with py launcher rather than needing python on the path for powershell as well.

**Comment by ramykl** [comment]
added a fix to the Powershell Fuck (PoShFuck) repository so it works again. Hopefully, the owner will merge it.
