### ISSUE TITLE
Traceback for pkg_resources not found

### ISSUE THREAD

**Issue by thibmaek** [nvbn/thefuck#124]
I figured out I needed to get psutil to get this working from the traceback but I installed it with brew, still getting the same error

- I'm using the brew version of thefuck

![screen shot 2015-04-24 at 20 20 40](https://cloud.githubusercontent.com/assets/6213695/7325610/b1b9ac16-eabf-11e4-821c-e9407d4cddd8.png)

![screen shot 2015-04-24 at 20 22 43](https://cloud.githubusercontent.com/assets/6213695/7325616/b4a00d3a-eabf-11e4-9813-6a637dc5a3b1.png)

**Comment by nvbn** [comment]
Brew package isn't official, so I can't change it. But your error can be fixed with:
```bash
pip install psutil
```

**Comment by scott-abernethy** [comment]
@thibmaek psutil is installed as a resource by the brew package, so you shouldn't need to install manually. What version did you install (brew list thefuck)?

@nvbn anyone can submit changes to brew if you need to make a fix.

**Comment by scott-abernethy** [comment]
PS the psutils package in brew is utilities for PostScript files. ;)

**Comment by scott-abernethy** [comment]
I don't think this is a problem with the brew package.

@thibmaek did you try to install thefuck with `pip` or `easy_install` before installing via brew? You will need to uninstall those as your path is picking that install over the brew install.

@nvbn the traceback indicates that the problem is with a local thefuck install, not the brew package. Brew packages install all python files under `/usr/local/...` and are independent of `.pyenv`. I.e. a problem with the brew package would have shown a traceback referencing `/usr/local/Cellar/thefuck/1.29/libexec/bin/thefuck`.

**Comment by thibmaek** [comment]
@scott-abernethy @nvbn well tbh, i got a pretty messed up install of pip on my machine, so maybe it would just be better to reinstall pip and try to install it with pip or easy_install.

Too bad that the brew version doesn't work out of the box when installing.

**Comment by thibmaek** [comment]
Uninstalled thefuck & psutils from brew. Reinstalled pip and works with package thefuck from pip.
Sorry for this thread.

**Comment by scott-abernethy** [comment]
@thibmaek the brew package does work out of the box, but didn't in your case because you'd installed via pip first. Glad you got it sorted. :smile:
