### ISSUE TITLE
If you become a Christian, what will you name this?

### ISSUE THREAD

**Issue by relipse** [nvbn/thefuck#1256]
What will you name this obscene program?

**Comment by jeffwalsh** [comment]
lmao

**Comment by SuperNici** [comment]
"gods gift"

**Comment by Rom1deTroyes** [comment]
«Holly Fuck», because that's Christmas break, and holly always seems holy. :angel:

**Comment by septatrix** [comment]
Honestly: What do you want to archive with this issue?

@nvbn has stated numerous times that he does not intent to change the name of this project (#66, https://github.com/nvbn/thefuck/issues/401#issuecomment-156984578, https://github.com/nvbn/thefuck/issues/801#issuecomment-380256406, #866, #1070). I am also fairly certain the maintainers are getting fed up with all these requests.

If you do not like to type some swear words you are free to register it under a different alias which is clearly documented how to do. You could even fork it and replace all occurrences of words you do not like with others.

Though be assured that you already converted one person to switch from the profane fuck. I now changed my alias to `please_help_me_satan` which I think is a lot nicer.

**Comment by SuperNici** [comment]
It feels more like a rhetorical question. Its meant to create a discussion. 

What would happen if @nvbn became a christian overnight? Could they live with themselves knowing that they made an application that depends on the usage of such 
oscene profanities? Or would they instead repent in order to be forgiven of their sins by renaming the project? If so what could possibly be a fitting name?

This question actually much deeper than it may seem, its an inquiry about the creators philosophy, morals, the way of life even. 🙏🙏🙏

**Comment by Explosion-Scratch** [comment]
> What will you name this obscene program?

If you become an atheist will you delete this issue

**Comment by AlfredEVOL** [comment]
### ThyFuck

**Comment by rayw000** [comment]
> ### ThyFuck

Didn't laugh until I saw your comment. 🤣

**Comment by ryleu** [comment]
> What will you name this obscene program?

If this repo were moved to me, a Christian, I would name it "thefuck".
