### ISSUE TITLE
Some things are more important than code.

### ISSUE THREAD

**Issue by patrick-gleeson** [nvbn/thefuck#1274]
Russians are being subjected to a campaign of lies by their own official media, meaning that, while thousands of Russians have died, and continue to die, in the ongoing invasion of Ukraine, their compatriots are neither being told about their deaths nor even what they died for.

Anyone who loves Russia should be concerned about this. The sudden censoring of Twitter and Facebook to prevent the truth from coming out mean Russians must find other ways to inform themselves. Please, learn and spread the truth. Start [here](https://acoup.blog/2022/02/25/miscellanea-understanding-the-war-in-ukraine/), continue [here](https://www.politico.eu/article/ukraine-war-russia-vladimir-putin-miscalculation/). Fight for truth.

**Comment by Dheirya** [comment]
Not the place.

**Comment by jacobmassengill** [comment]
> Not the place.

While I tend to agree, because I like to think that open source and development in general is a nice little well-structured and logical oasis from the rest of the world, I'm hesitant. if the people of russia feel this desperate that they need to use a random open source library issues page, should we stop it? I understand the myriad of implications to allowing it (spam, the appearance of taking a side), but if it saves even a single life, is it a moral obligation? 

food for thought, and ready for healthy discussion. personally, I'm torn.

**Comment by SherkeyXD** [comment]
github is not for political use
