### ISSUE TITLE
Running 'fuck' successfully removes history entries made in that session

### ISSUE THREAD

**Issue by eyalzek** [nvbn/thefuck#191]
Reproduction:
open a new shell, click the up arrow to view the latest entry in bash_history ->
enter a few more commands -> enter a command that can be fixed with thefuck ->
run fuck (aliased to: 'eval $(thefuck $(fc -ln -1)); history -r') ->
click the up arrow -> all the commands entered in that shell are gone, the history is the same as if you just opened a new shell.

Is this expected, am I doing something wrong?

**Comment by dunn** [comment]
Same for me on bash 4.3.33.

Maybe `history -r` should be replaced with `history -a; history -c; history -r`? Append to the history file, then clear and re-read.

**Comment by eyalzek** [comment]
I'm on bash 4.3.11(1)-release BTW.

I changed the alias as you suggested and it seems to act correctly, so I'm going to leave it like that for now :)

**Comment by underscorejho** [comment]
While trying to programmatically fetch history (instead of using the alias) on #167 (relevant code is in get_command() in main.py) , I figured out that the following lines in your .bashrc will keep your .bash_history current with each command:

    shopt -s histappend
    PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

This executes PROMPT_COMMAND just before displaying each new command prompt, so it is actively updating your .bash_history with each command.

I'm not 100% certain that this'll solve the problem, but it could help.

**Comment by dunn** [comment]
Yeah, currently I've got 
```bash
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r";
```
in `.bashrc` (see https://unix.stackexchange.com/questions/1288/preserve-bash-history-in-multiple-terminal-windows) and my `fuck` alias is back to `alias fuck='thefuck $(fc -ln -1)'`

**Comment by ogarcia** [comment]
Fuck, fucks itself. :smile:

The good alias is: `alias fuck='eval $(thefuck $(fc -ln -1))`. Or much simply as @dunn comment `alias fuck='thefuck $(fc -ln -1)` cause not is necessary make an eval.

And this alias only work in bash, cause in you sh cannot make the bash expansion `$()`.

What is clear is that the `history -r` is a bad thing.

**Comment by nbelakovski** [comment]
dunn's suggestion for `history -a; history -c` worked for me. I think underscorejho's suggestion will have some other side effects, like your history doesn't get stored for a single terminal session (since, usually, history is contained in memory and written to disk on exit of a shell, whereas the suggestion changes it to write to disk on every command).

Ideally this could be fixed within thefuck, instead of outside hacks like this. I've noticed that thefuck seems to duplicate the history, since I see double the entries in history after running `fuck`. It probably shouldn't be editing the history at all.

**Comment by nvbn** [comment]
The way of handling history was changed in previous releases.
