### ISSUE TITLE
Should suggest 'git tag' when typing 'git tags' instead of 'git stage'

### ISSUE THREAD

**Issue by hanxue** [nvbn/thefuck#229]
```
$ git tags
git: 'tags' is not a git command. See 'git --help'.

Did you mean one of these?
	stage
	tag
$ fuck
git stage
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
```

Any way to improve the suggestion in this case?

**Comment by scorphus** [comment]
Yes, there is! Would you like to dig this one?

**Comment by waldyrious** [comment]
@scorphus can you offer some more info about how to do this? [I see](../tree/master/thefuck/rules) lots of `git_*.py` files but no `git_tag.py`, so I assume this situation is being captured by a more generic rule, but which?

**Comment by scorphus** [comment]
`git_not_command.py` is your rule

**Comment by scorphus** [comment]
Also, take a look at `mercurial.py` if you'd like some hints.

**Comment by nvbn** [comment]
Should work properly in 1.48+

**Comment by scorphus** [comment]
Nice, @nvbn! I really like your solution! :+1: It's just a pity that you gave @waldyrious no chance to try :stuck_out_tongue_winking_eye:

**Comment by waldyrious** [comment]
I actually wouldn't, @scorphus. I truly appreciate your attempt to onboard new contributors, but remember that not everyone has sufficient background knowledge for the amount of information you provided to be useful/encouraging (it wasn't for me). Of course, you guys might prefer to attract people with more python/git/whatever proficiency, but I personally believe there's more to gain in this kind of collaborative projects by lowering the bar for new contributors.

**Comment by scorphus** [comment]
Oh, I'm very sorry if I sounded like not wanting to give you more information, @waldyrious, my bad. It's quite the contrary in fact. But I tend not to give all the hints at once.

It may be a fault of mine, I don't know. But I believe we learn more from trying to figure things out by ourselves and making questions along the way than from others telling us what to do and how. On the other hand, you could have asked for more information and I'd happily reply, like gradually lowering the bar :smiley:

**Comment by waldyrious** [comment]
It's ok, I don't hold any hard feelings regarding you personally, I'm just trying to make my perspective clear. Note that I did ask for more information once, which you sounded reluctant on giving, therefore I'd say it's pretty natural to expect that one wouldn't feel compelled to keep asking unless they were already highly motivated.

Mind you, I completely agree that one learns best (more solidly) by experimenting rather than having things presented to them pre-digested. Unfortunately, people don't always have the time or the skill (or neither) to engage in this longer and more prolific process, so the easier route is often better in terms of actually getting things done (as I mentioned, I had given up offering my help here, and this is especially true for new contributors who aren't yet invested in the project).

In the end, I guess we kinda agree, it just boils down to recognizing the importance of assessing the involvement/investment and background knowledge shown by a prospective contributor, and adjusting the degree of assistance accordingly. (Or, you know, simply erring on the side of extra help rather than withholding information, especially since one person's Q&A serves as RTFM material for those who come afterwards).

**Comment by scorphus** [comment]
I agree with you. Yet I'm sorry for not careful reading your message. Had I read it more heedful I'd have replied accordingly, which I didn't. I'll keep this advice and use it the next time I try to onboard a new contributor. Thank you.

**Comment by waldyrious** [comment]
Yeah, online communication is hard -- again, no hard feelings at all. Besides, I'm happy if sometime in the future this exchange enables a prospective contributor to become engaged with a project you're involved in when otherwise they wouldn't. I think that's a win for everyone :)
