### ISSUE TITLE
Usage freezes terminal in Windows

### ISSUE THREAD

**Issue by pingzing** [nvbn/thefuck#378]
Invoking `thefuck` in any way causes my terminal to lock up, using any shell--Powershell (via ConEmu) vanilla Powershell, or msysgit's git bash.

For example, `thefuck git brnch` outputs a slightly malformed suggestion of "git branch" and then stops accepting user input entirely.

I'm running Windows 10 and 32-bit Python 3.5.0.

Powershell
![fuck](https://cloud.githubusercontent.com/assets/5133649/10382102/3043a6f8-6e29-11e5-9f2d-75436bd85696.png)

Git bash
![fuck](https://cloud.githubusercontent.com/assets/5133649/10382113/462c12f2-6e29-11e5-8bb6-f31b58d00d1e.png)

**Comment by hchokshi** [comment]
I'm also experiencing the same issue using Powershell and the msysgit bundled with Github for Desktop. Shows the correct command suggestion, but doesn't take any input after that.

I'm also seeing \u2191 and \u2198 in the console like you are, here. I doubt this is intentional. 

These issues are experienced directly opening Powershell / bash and using them through cmder.

**Comment by TAGC** [comment]
I'm experiencing this as well (through both Cygwin and Git Bash for Windows).

**Comment by scharney** [comment]
Sorry to necro-post, but I'm having this same issue, and I'm not sure what's causing it. I'd love to be able to get it to work if anyone has suggestions! I'm using git bash on Windows 11.
