### ISSUE TITLE
Error unknown option

### ISSUE THREAD

**Issue by shiro-42** [nvbn/thefuck#601]
Hello, I have this error every time I use fuck `history: Unknown option '--exact'`
How to reproduce: use the fuck

The Fuck 3.14 using Python 2.7.10
fish, version 2.3.1
mac OS Sierra 10.12.2

**Comment by mylyed** [comment]
fuck!

**Comment by scorphus** [comment]
We're always trying to keep up with new stable releases of Fish Shel. Since [2.4](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md#fish-240-released-november-8-2016) there were some rather big changes to history management. Hence the new `--exact` option. Check #577 for reference.

If upgrading to newer versions of Fish Shell is not an option, you can disable history alteration with an entry `alter_history = False` in your [settings](https://github.com/nvbn/thefuck#settings).

Sorry for any inconvenience.

I hope this helps.

**Comment by jspiro** [comment]
Seems like this should be closed
