### ISSUE TITLE
idea: fuck-it repeatedly until command works

### ISSUE THREAD

**Issue by jedwards1211** [nvbn/thefuck#614]
In the example gif it takes two fucks to correct `aptget install ...`, one to fix `apt-get` and one to insert `sudo`.

Might be cool if there were a single command that keeps retrying the default fuck every time the previous command fails, in this case it would apply both of those fucks automatically.  Command could be `fuck it all` or `fuck my life` 😆

**Comment by yashpatel5400** [comment]
Haha, I'm down to put this feature in

**Comment by yashpatel5400** [comment]
Actually, after thinking about this feature for a little, it seems like it might just cause more frustration on the user end, since if we did "aptget instll -f" or something and did a fuck-it, the tool would default to "apt-get install." Should be possible once the corrector becomes really accurate though

**Comment by nvbn** [comment]
Because of #620 now we can have something like this:

![tty](https://cloud.githubusercontent.com/assets/1114542/24415812/0682ffec-13e3-11e7-9622-d10ba60fd376.gif)

**Comment by jedwards1211** [comment]
awesome, thanks!  I will basically think of `fuck -r` as the "fucker" command 😆

**Comment by nvbn** [comment]
Implemented in 3.16.
