### ISSUE TITLE
What if FUCK is misspelled?

### ISSUE THREAD

**Issue by ganeshredcobra** [nvbn/thefuck#74]
What if we mistype Fuck? It will Fuck us ultimately :)

![screenshot from 2015-04-21 17 33 12](https://cloud.githubusercontent.com/assets/265046/7251859/ac66b756-e84c-11e4-8624-3fe52032cc39.png)

**Comment by nvbn** [comment]
Probably fixed in 1.23+

**Comment by ja5h** [comment]
I verified this and it has been fixed in the newest version.

**Comment by Clpsplug** [comment]
Verified here as well, it won't fuck us up - *but!* I think this is not it's meant to be...

![fuck didn't add sudo](http://i.gyazo.com/e47d560c5022e18706fd73597241573a.png)

#### What I did here:
I can't do `mkdir` at `/` without sudo which I did, and accidentally ran `fuk` instead of `fuck`. Dissatisfied, I ran `fuck`.

#### What actually happened

1. `fuck` went to get the last command, which resulted in getting `fuk`
2. `fuck` thought I meant `thefuck` (or alias `fuck`), and ran it for me
3. But for some reason that `thefuck` (which have just been run by `thefuck`) didn't get the *2nd latest command* (which is `mkdir a` ran at the root) and didn't give any fuck. 

#### What I expected

1. `fuck` goes to get the last command, which results in getting `fuk`
2. `fuck` thinks I meant `thefuck` (or alias `fuck`), and runs it for me
3. *This `fuck` (which been run by `thefuck`) gets*  **its**  *last command, `mkdir a`.*
4. *`fuck` thinks I skipped `sudo`, and it runs my command with `sudo`, resulting in running `sudo mkdir a`.* 

Can this be implemented? - like, **whenever `thefuck` tries to correct itself, it'll get the 2nd latest command.**

**Comment by scorphus** [comment]
Fixed in 9ba36c9
